-- MySQL Script generated by MySQL Workbench
-- Wed Sep  9 11:59:29 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bt_phantichvathietkecsdl
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bt_phantichvathietkecsdl
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bt_phantichvathietkecsdl` DEFAULT CHARACTER SET utf8 ;
USE `bt_phantichvathietkecsdl` ;

-- -----------------------------------------------------
-- Table `bt_phantichvathietkecsdl`.`offices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt_phantichvathietkecsdl`.`offices` (
  `officeCode` VARCHAR(10) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(50) NOT NULL,
  `addressLine1` VARCHAR(50) NOT NULL,
  `addressLine2` VARCHAR(50) NULL DEFAULT NULL,
  `state` VARCHAR(50) NULL DEFAULT NULL,
  `country` VARCHAR(50) NOT NULL,
  `postalCode` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`officeCode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bt_phantichvathietkecsdl`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt_phantichvathietkecsdl`.`employees` (
  `employeeNumber` INT NOT NULL,
  `lastName` VARCHAR(50) NOT NULL,
  `firstName` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `jobTitle` VARCHAR(50) NOT NULL,
  `reportTo` INT NOT NULL,
  `officeCode` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`employeeNumber`),
  INDEX `officeCode` (`officeCode` ASC) VISIBLE,
  INDEX `reportTo` (`reportTo` ASC) VISIBLE,
  CONSTRAINT `employees_ibfk_1`
    FOREIGN KEY (`officeCode`)
    REFERENCES `bt_phantichvathietkecsdl`.`offices` (`officeCode`),
  CONSTRAINT `employees_ibfk_2`
    FOREIGN KEY (`officeCode`)
    REFERENCES `bt_phantichvathietkecsdl`.`offices` (`officeCode`),
  CONSTRAINT `employees_ibfk_3`
    FOREIGN KEY (`reportTo`)
    REFERENCES `bt_phantichvathietkecsdl`.`employees` (`employeeNumber`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bt_phantichvathietkecsdl`.`customes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt_phantichvathietkecsdl`.`customes` (
  `customerNumber` INT NOT NULL,
  `customerName` VARCHAR(50) NOT NULL,
  `contactLastName` VARCHAR(50) NOT NULL,
  `contactFirstName` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(50) NOT NULL,
  `addressLine1` VARCHAR(50) NOT NULL,
  `addressLine2` VARCHAR(50) NULL DEFAULT NULL,
  `city` VARCHAR(50) NOT NULL,
  `state` VARCHAR(50) NOT NULL,
  `postalCode` VARCHAR(15) NOT NULL,
  `country` VARCHAR(50) NOT NULL,
  `creditLimit` DECIMAL(10,2) NULL DEFAULT NULL,
  `salesRepEmployeeNumber` INT NOT NULL,
  PRIMARY KEY (`customerNumber`),
  INDEX `salesRepEmployeeNumber` (`salesRepEmployeeNumber` ASC) VISIBLE,
  CONSTRAINT `customes_ibfk_1`
    FOREIGN KEY (`salesRepEmployeeNumber`)
    REFERENCES `bt_phantichvathietkecsdl`.`employees` (`employeeNumber`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bt_phantichvathietkecsdl`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt_phantichvathietkecsdl`.`orders` (
  `orderNumber` INT NOT NULL,
  `orderDate` DATE NOT NULL,
  `requiredDate` DATE NOT NULL,
  `shippedDate` DATE NULL DEFAULT NULL,
  `status` VARCHAR(10) NOT NULL,
  `comments` TEXT NULL DEFAULT NULL,
  `quantityOrdered` INT NOT NULL,
  `priceEach` FLOAT NOT NULL,
  `customerNumber` INT NOT NULL,
  PRIMARY KEY (`orderNumber`),
  INDEX `orders_ibfk_1` (`customerNumber` ASC) VISIBLE,
  CONSTRAINT `orders_ibfk_1`
    FOREIGN KEY (`customerNumber`)
    REFERENCES `bt_phantichvathietkecsdl`.`customes` (`customerNumber`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bt_phantichvathietkecsdl`.`productslines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt_phantichvathietkecsdl`.`productslines` (
  `productline` VARCHAR(50) NOT NULL,
  `textDescription` VARCHAR(45) NULL DEFAULT NULL,
  `image` MEDIUMBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`productline`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bt_phantichvathietkecsdl`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt_phantichvathietkecsdl`.`products` (
  `productCode` VARCHAR(15) NOT NULL,
  `productName` VARCHAR(70) NOT NULL,
  `productScale` VARCHAR(10) NOT NULL,
  `productVendor` VARCHAR(50) NOT NULL,
  `productDescription` TEXT NOT NULL,
  `quantityInStock` INT NOT NULL,
  `buyPrice` DECIMAL(10,2) NOT NULL,
  `MSRP` DECIMAL(10,2) NOT NULL,
  `productLine` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`productCode`),
  INDEX `productLine` (`productLine` ASC) VISIBLE,
  CONSTRAINT `products_ibfk_1`
    FOREIGN KEY (`productLine`)
    REFERENCES `bt_phantichvathietkecsdl`.`productslines` (`productline`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bt_phantichvathietkecsdl`.`orderdetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt_phantichvathietkecsdl`.`orderdetails` (
  `orderNumber` INT NOT NULL,
  `productCode` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`orderNumber`, `productCode`),
  INDEX `productCode` (`productCode` ASC) VISIBLE,
  CONSTRAINT `orderdetails_ibfk_1`
    FOREIGN KEY (`orderNumber`)
    REFERENCES `bt_phantichvathietkecsdl`.`orders` (`orderNumber`),
  CONSTRAINT `orderdetails_ibfk_2`
    FOREIGN KEY (`productCode`)
    REFERENCES `bt_phantichvathietkecsdl`.`products` (`productCode`),
  CONSTRAINT `orderdetails_ibfk_3`
    FOREIGN KEY (`productCode`)
    REFERENCES `bt_phantichvathietkecsdl`.`products` (`productCode`),
  CONSTRAINT `orderdetails_ibfk_4`
    FOREIGN KEY (`orderNumber`)
    REFERENCES `bt_phantichvathietkecsdl`.`orders` (`orderNumber`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bt_phantichvathietkecsdl`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt_phantichvathietkecsdl`.`payments` (
  `customerNumber` INT NOT NULL,
  `checkNumber` VARCHAR(50) NOT NULL,
  `paymentDate` DATE NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`customerNumber`),
  CONSTRAINT `payments_ibfk_1`
    FOREIGN KEY (`customerNumber`)
    REFERENCES `bt_phantichvathietkecsdl`.`customes` (`customerNumber`),
  CONSTRAINT `payments_ibfk_2`
    FOREIGN KEY (`customerNumber`)
    REFERENCES `bt_phantichvathietkecsdl`.`customes` (`customerNumber`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bt_phantichvathietkecsdl`.`Hello`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt_phantichvathietkecsdl`.`Hello` (
  `idHello` INT NOT NULL,
  PRIMARY KEY (`idHello`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
