-- MySQL Script generated by MySQL Workbench
-- Mon Oct  5 15:05:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema product
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema product
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `product` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `product` ;

-- -----------------------------------------------------
-- Table `product`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product`.`category` (
  `IdCategory` INT NOT NULL AUTO_INCREMENT,
  `Category Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdCategory`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `product`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `productName` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  `amount` INT NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `category_IdCategory` INT NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_category_idx` (`category_IdCategory` ASC) VISIBLE,
  CONSTRAINT `fk_products_category`
    FOREIGN KEY (`category_IdCategory`)
    REFERENCES `product`.`category` (`IdCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `product` ;

-- -----------------------------------------------------
-- procedure get_product_by_id
-- -----------------------------------------------------

DELIMITER $$
USE `product`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `get_product_by_id`(IN product_id INT)
BEGIN

    SELECT products.productName, products.price, products.amount, products.color, products.description

    FROM products

    where products.id = product_id;

    END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insert_product
-- -----------------------------------------------------

DELIMITER $$
USE `product`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insert_product`(

IN product_name varchar(50),

IN product_price float,

IN product_amount int,

IN product_color varchar(50),

IN product_description varchar(50)

)
BEGIN

    INSERT INTO products(productName, price, amount, color, description) VALUES(product_name, product_price, product_amount, product_color, product_description);
    END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
